//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.PowerToys.Run.Plugin._1Password.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Community.PowerToys.Run.Plugin._1Password.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        internal static string one_password_domain {
            get {
                return ResourceManager.GetString("one_password_domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a vault to never load. This takes priority, event if an item in the vault is favorited..
        /// </summary>
        internal static string one_password_exclude_vault_desc {
            get {
                return ResourceManager.GetString("one_password_exclude_vault_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Vault.
        /// </summary>
        internal static string one_password_exlude_vault {
            get {
                return ResourceManager.GetString("one_password_exlude_vault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preload Vault.
        /// </summary>
        internal static string one_password_init_vault {
            get {
                return ResourceManager.GetString("one_password_init_vault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a vault to always keep loaded for search. Note: this only keeps the id and name of the vault loaded..
        /// </summary>
        internal static string one_password_init_vault_desc {
            get {
                return ResourceManager.GetString("one_password_init_vault_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Path.
        /// </summary>
        internal static string one_password_install_path {
            get {
                return ResourceManager.GetString("one_password_install_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the one password cli exe called op.exe.
        /// </summary>
        internal static string one_password_install_path_desc {
            get {
                return ResourceManager.GetString("one_password_install_path_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preload Favorites.
        /// </summary>
        internal static string one_password_preload_favorite {
            get {
                return ResourceManager.GetString("one_password_preload_favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KairuDeibisu.
        /// </summary>
        internal static string plugin_author {
            get {
                return ResourceManager.GetString("plugin_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search 1Password for usernames and passwords.
        /// </summary>
        internal static string plugin_description {
            get {
                return ResourceManager.GetString("plugin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1Password.
        /// </summary>
        internal static string plugin_name {
            get {
                return ResourceManager.GetString("plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1Password Settings.
        /// </summary>
        internal static string plugin_setting {
            get {
                return ResourceManager.GetString("plugin_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows History.
        /// </summary>
        internal static string windows_enable_history {
            get {
                return ResourceManager.GetString("windows_enable_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Copied item to show in windows history.
        /// </summary>
        internal static string windows_enable_history_desc {
            get {
                return ResourceManager.GetString("windows_enable_history_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Roaming.
        /// </summary>
        internal static string windows_enable_roaming {
            get {
                return ResourceManager.GetString("windows_enable_roaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Copied item to show accross devices.
        /// </summary>
        internal static string windows_enable_roaming_desc {
            get {
                return ResourceManager.GetString("windows_enable_roaming_desc", resourceCulture);
            }
        }
    }
}
